// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BanUser(ctx context.Context, arg BanUserParams) error
	CountUsers(ctx context.Context, search string) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTwoFactor(ctx context.Context, arg CreateTwoFactorParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateVerification(ctx context.Context, arg CreateVerificationParams) error
	DeleteAccount(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) error
	DeleteExpiredVerifications(ctx context.Context, expiresAt pgtype.Timestamptz) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionByToken(ctx context.Context, token string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteTwoFactorByUserID(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteVerification(ctx context.Context, id string) error
	GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error)
	GetCredentialByUserID(ctx context.Context, userID string) (Account, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetTwoFactorByUserID(ctx context.Context, userID string) (TwoFactor, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetVerificationByIdentifier(ctx context.Context, identifier string) (Verification, error)
	ListAccountsByUserID(ctx context.Context, userID string) ([]Account, error)
	ListSessionsByUserID(ctx context.Context, userID string) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetTwoFactorVerified(ctx context.Context, arg SetTwoFactorVerifiedParams) error
	SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	SetUserTwoFactorEnabled(ctx context.Context, arg SetUserTwoFactorEnabledParams) error
	UnbanUser(ctx context.Context, arg UnbanUserParams) error
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
	UpdateTwoFactorBackupCodes(ctx context.Context, arg UpdateTwoFactorBackupCodesParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
