// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: two_factor.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTwoFactor = `-- name: CreateTwoFactor :exec
INSERT INTO two_factors (id, user_id, secret, backup_codes, verified, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTwoFactorParams struct {
	ID          string
	UserID      string
	Secret      string
	BackupCodes string
	Verified    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateTwoFactor(ctx context.Context, arg CreateTwoFactorParams) error {
	_, err := q.db.Exec(ctx, createTwoFactor,
		arg.ID,
		arg.UserID,
		arg.Secret,
		arg.BackupCodes,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTwoFactorByUserID = `-- name: DeleteTwoFactorByUserID :exec
DELETE FROM two_factors
WHERE user_id = $1
`

func (q *Queries) DeleteTwoFactorByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteTwoFactorByUserID, userID)
	return err
}

const getTwoFactorByUserID = `-- name: GetTwoFactorByUserID :one
SELECT id, user_id, secret, backup_codes, verified, created_at, updated_at FROM two_factors
WHERE user_id = $1
`

func (q *Queries) GetTwoFactorByUserID(ctx context.Context, userID string) (TwoFactor, error) {
	row := q.db.QueryRow(ctx, getTwoFactorByUserID, userID)
	var i TwoFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.BackupCodes,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTwoFactorVerified = `-- name: SetTwoFactorVerified :exec
UPDATE two_factors
SET verified = $2, updated_at = $3
WHERE user_id = $1
`

type SetTwoFactorVerifiedParams struct {
	UserID    string
	Verified  bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetTwoFactorVerified(ctx context.Context, arg SetTwoFactorVerifiedParams) error {
	_, err := q.db.Exec(ctx, setTwoFactorVerified, arg.UserID, arg.Verified, arg.UpdatedAt)
	return err
}

const updateTwoFactorBackupCodes = `-- name: UpdateTwoFactorBackupCodes :exec
UPDATE two_factors
SET backup_codes = $2, updated_at = $3
WHERE user_id = $1
`

type UpdateTwoFactorBackupCodesParams struct {
	UserID      string
	BackupCodes string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateTwoFactorBackupCodes(ctx context.Context, arg UpdateTwoFactorBackupCodesParams) error {
	_, err := q.db.Exec(ctx, updateTwoFactorBackupCodes, arg.UserID, arg.BackupCodes, arg.UpdatedAt)
	return err
}
