// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE users
SET banned = true, ban_reason = $2, ban_expires = $3, updated_at = $4
WHERE id = $1
`

type BanUserParams struct {
	ID         string
	BanReason  *string
	BanExpires pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser,
		arg.ID,
		arg.BanReason,
		arg.BanExpires,
		arg.UpdatedAt,
	)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR name ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, email, email_verified, image, role, two_factor_enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID               string
	Name             string
	Email            string
	EmailVerified    bool
	Image            *string
	Role             string
	TwoFactorEnabled bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
		arg.Image,
		arg.Role,
		arg.TwoFactorEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, image, role, created_at, updated_at, two_factor_enabled, banned, ban_reason, ban_expires
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorEnabled,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, role, created_at, updated_at, two_factor_enabled, banned, ban_reason, ban_expires
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorEnabled,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, email_verified, image, role, created_at, updated_at, two_factor_enabled, banned, ban_reason, ban_expires
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TwoFactorEnabled,
			&i.Banned,
			&i.BanReason,
			&i.BanExpires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, email_verified, image, role, created_at, updated_at, two_factor_enabled, banned, ban_reason, ban_expires
FROM users
WHERE ($1::text = '' OR email ILIKE '%' || $1::text || '%' OR name ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type SearchUsersParams struct {
	Search string
	Off    int32
	Lim    int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TwoFactorEnabled,
			&i.Banned,
			&i.BanReason,
			&i.BanExpires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified = $2, updated_at = $3
WHERE id = $1
`

type SetUserEmailVerifiedParams struct {
	ID            string
	EmailVerified bool
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, arg.ID, arg.EmailVerified, arg.UpdatedAt)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users
SET role = $2, updated_at = $3
WHERE id = $1
`

type SetUserRoleParams struct {
	ID        string
	Role      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role, arg.UpdatedAt)
	return err
}

const setUserTwoFactorEnabled = `-- name: SetUserTwoFactorEnabled :exec
UPDATE users
SET two_factor_enabled = $2, updated_at = $3
WHERE id = $1
`

type SetUserTwoFactorEnabledParams struct {
	ID               string
	TwoFactorEnabled bool
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) SetUserTwoFactorEnabled(ctx context.Context, arg SetUserTwoFactorEnabledParams) error {
	_, err := q.db.Exec(ctx, setUserTwoFactorEnabled, arg.ID, arg.TwoFactorEnabled, arg.UpdatedAt)
	return err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users
SET banned = false, ban_reason = NULL, ban_expires = NULL, updated_at = $2
WHERE id = $1
`

type UnbanUserParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UnbanUser(ctx context.Context, arg UnbanUserParams) error {
	_, err := q.db.Exec(ctx, unbanUser, arg.ID, arg.UpdatedAt)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = $2, email = $3, email_verified = $4, image = $5, role = $6, updated_at = $7
WHERE id = $1
`

type UpdateUserParams struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         *string
	Role          string
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
		arg.Image,
		arg.Role,
		arg.UpdatedAt,
	)
	return err
}
