// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :exec
INSERT INTO verifications (id, identifier, value, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateVerificationParams struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification,
		arg.ID,
		arg.Identifier,
		arg.Value,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredVerifications = `-- name: DeleteExpiredVerifications :exec
DELETE FROM verifications
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredVerifications(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerifications, expiresAt)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
DELETE FROM verifications
WHERE id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVerification, id)
	return err
}

const getVerificationByIdentifier = `-- name: GetVerificationByIdentifier :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM verifications
WHERE identifier = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetVerificationByIdentifier(ctx context.Context, identifier string) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByIdentifier, identifier)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
